-- load plugin settings:
require("plugs.colorscheme")
require("plugs.lualine")
require("plugs.barbar")

require("plugs.cmp")
require("plugs.lsp")
require("plugs.telescope")
require("plugs.nvimlastplace")
require("plugs.nvimcomment")
require("plugs.null_ls")
require("plugs.symbols_outline")
require("plugs.others")
require("plugs.oil")
require("plugs.conform")
