-- load plugin settings:
require 'plugs.colorscheme'
require 'plugs.lualine'
require 'plugs.treesitter'
require 'plugs.barbar'

require 'plugs.cmp'
require 'plugs.project'
require 'plugs.mason'
require 'plugs.lsp'
require 'plugs.telescope'
require 'plugs.nvimtree'
require 'plugs.nvimlastplace'
require 'plugs.nvimcomment'
require 'plugs.trouble'
require 'plugs.session'
require 'plugs.gitsigns'
require 'plugs.osc52'
