require 'keymapping'
require 'optset'
require 'PlugInstall'
require 'plugs/onedark'
require 'plugs/lualine'
require 'plugs/treesitter'
require 'plugs/barbar'
require 'plugs/clangformat'
require 'plugs/cmp'
require 'plugs/project'
require 'plugs/lsp'

